---
security_ssh_port: 666
# Antigen / ZSH vars
antigen_install_oh_my_zsh: yes
ansible_ssh_user: rbw

username: rbw

zshrc_home: $HOME/.zshrc
zshrc_repo: $HOME/repo/dotfiles-rbw/home/.zshrc
home_repo: $HOME/repo/dotfiles-rbw/home