all:
  children:
    arch:
      hosts:
        arch:
          ansible_host: 192.168.0.118
    dev:
      hosts:
        dev1:
          ansible_host: 192.168.0.140
          # ansible_host: 34.116.244.218
    ubuntu:
      hosts:
        ubuntu:
          ansible_host: 192.168.0.39
  vars:
    ansible_ssh_user:
      rbw
    ansible_ssh_port:
      22
